# coding: utf-8

# flake8: noqa
"""
    Sample API

    Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.  # noqa: E501

    OpenAPI spec version: 0.1.9
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
