name: CD - Publish Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-doc.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code from tag branch
        uses: actions/checkout@v3

      - name: Publish Release
        run: |
          echo "release: ${{ github.event.release.tag_name }}"
