name: Check - All linters, etc
on:
  push:
    branches:
      - main
      - release-*
    tags-ignore:
      - "**"

jobs:
  build:
    name: Change to Main/Release Branch
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v1

      - name: Ensure dependencies installed
        shell: bash
        run: |
          make ensure-deps

      - name: Run all checks
        shell: bash
        run: |
          make check
